### ISSUE TITLE
Tabs do not resize correctly on zoom.

### ISSUE THREAD

**Issue by DanielFitzsimmons** [iocave/customize-ui#137]
Tabs do not resize correctly on zoom.
https://www.icloud.com/iclouddrive/04admHCHbksiVcFXJCe7UTZ_Q#tabs

**Comment by jdmansour** [comment]
The issue seems to be the following code in `customize-ui.css`:

```css
body.inline-title-bar .monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container,
body.inline-title-bar .monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab,
body.inline-title-bar .monaco-workbench .part.editor>.content .editor-group-container>.title .editor-actions {
    height: var(--traffic-lights-height) !important;
    line-height: var(--traffic-lights-height) !important;
}
```

If you comment it out with the inspector, the tabs resize properly. They don't align anymore with the window controls, but that doesn't bother me.
