### ISSUE TITLE
Set multiple fonts to customizeUI.font.regular

### ISSUE THREAD

**Issue by jcastrov** [iocave/customize-ui#30]
Is there a way to set multiple fonts to Regular type?
```javascript
{
    // Works
    "editor.fontFamily": "Monaco, 'Courier New', monospace",

    // Works
    "customizeUI.font.regular": "Monaco",

    // Fails
    "customizeUI.font.regular": "Monaco, 'Courier New', monospace" 
}
```

I use the same `settings.json` in different Operative systems, but the Monaco font is not installed in all of them. Or maybe is there another way to replicate that behavior? 
> If Monaco is not installed, then use Courier New and so on

**Comment by jcastrov** [comment]
I see the problem, the style is adding quotation marks to the whole fonts string
```css
.mac, .windows, .linux {
    font-family: "Monaco, 'Courier New'" !important;
}
```

You should try to edit the string first
```css
.mac, .windows, .linux {
    font-family: Monaco, "Courier New" !important;
}
```
