### ISSUE TITLE
Suggestion: Customise font-size and transparency of the minimap

### ISSUE THREAD

**Issue by Hultner** [iocave/customize-ui#4]
The built in mini-map is very limited in customisation. 
It doesn't change size when you update the zoom level (I've used zoom level -3 to make UI-elements take up less editing space), you can only restrict it to to a character width which isn't that useful. Being able to scale it down or change the font size (or up for certain users) would be much more useful.

In my use case I'd like to keep it to provide a quick outline of the file but I'd like it scaled down to maybe half the size.

Additionally it would be very useful if it could be made transparent/floating like in Atom, thus allowing lines to show through and beneath it.

**Comment by dpren** [comment]
For transparency, try these styles I wrote:

```css
.minimap-shadow-visible {
  display: none !important;
}

.minimap > canvas:first-of-type {
  opacity: 0.5;
  filter: brightness(160%) contrast(120%);
}
```
(I personally use [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) for this)

The minimap is a canvas, so it required some filter hackery to get passable "background opacity". Changing font-size would involve modifying the JS source – In which case you'd probably just as well file a PR with vscode.
