### ISSUE TITLE
[Request] Allow dragging side-bar when using inline titleBar

### ISSUE THREAD

**Issue by lehni** [iocave/customize-ui#74]
In `[vscode-titlebar-less-macos](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-titlebar-less-macos)` I used this simple CSS to achieve this affect. Could something like this be added to `customize-ui`?

```css
/* Allow dragging on the activity-bar... */
.monaco-workbench.titlebar-less:not(.fullscreen) .activitybar {
  -webkit-app-region: drag;
}

/* ...but still allow to click actions without dragging */
.monaco-workbench.titlebar-less:not(.fullscreen) .activitybar .content .monaco-action-bar {
  -webkit-app-region: no-drag;
}

 /* Allow dragging on side-bar title... */
 .monaco-workbench.titlebar-less:not(.fullscreen) .sidebar .composite.title {
  -webkit-app-region: drag;
}
/* ...but still allow to click actions without dragging. */
.monaco-workbench.titlebar-less:not(.fullscreen) .sidebar .title .title-actions .action-label {
  -webkit-app-region: no-drag;
}
```
